default: true
MD007:
  indent: 2
MD013:
  line_length: 100
  heading_line_length: 100
  code_block_line_length: 100
  code_blocks: true
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false
MD024:
  siblings_only: true
